### ISSUE TITLE
Missing Icons result in unsightly overlapping text

### ISSUE THREAD

**Issue by ptrsmk** [community-scripts/Proxmox#2]
Raised in the other repository. Closing there and opening here.

**Describe the bug**
Missing Icons result in unsightly overlapping text

**To Reproduce**
View the homepage.

**Screenshots**
![image](https://github.com/user-attachments/assets/28ebefc4-098c-41f0-8c3c-8373fdd88269)

**Additional context**
https://github.com/community-scripts/ProxmoxVE/discussions/4

**Comment by BramSuurdje** [comment]
Issue has been fixes with commit 217a734
